import { CATALOG } from "./catalog";
import { fromMicroUsdc, toMicroUsdc } from "./config";
import { getSql } from "./neon";
import { voucherCode } from "./order-token";
import type { Order, Product, Voucher, VoucherRow, VoucherStatus } from "./db";

const globalForNeonShop = globalThis as typeof globalThis & {
  __voucherShopNeonReady?: Promise<void>;
};

function toIso(value: unknown): string {
  if (value instanceof Date) return value.toISOString();
  const raw = String(value);
  if (raw.includes("T")) return new Date(raw).toISOString();
  return new Date(`${raw.replace(" ", "T")}Z`).toISOString();
}

function asProduct(row: Record<string, unknown>): Product {
  return {
    id: Number(row.id),
    slug: String(row.slug),
    brand: String(row.brand),
    name: String(row.name),
    description: String(row.description),
    category: String(row.category),
    usd_value: Number(row.usd_value),
    price_micro: Number(row.price_micro),
    theme: String(row.theme),
    active: Number(row.active),
    created_at: toIso(row.created_at),
  };
}

function asOrder(row: Record<string, unknown>): Order {
  return {
    id: String(row.id),
    product_id: Number(row.product_id),
    quantity: Number(row.quantity),
    buyer_address: row.buyer_address == null ? null : String(row.buyer_address),
    amount_micro: Number(row.amount_micro),
    derivation_index: Number(row.derivation_index),
    tx_hash: row.tx_hash == null ? null : String(row.tx_hash),
    status: row.status as Order["status"],
    created_at: toIso(row.created_at),
    paid_at: row.paid_at == null ? null : toIso(row.paid_at),
  };
}

function asVoucher(row: Record<string, unknown>): Voucher {
  return {
    id: Number(row.id),
    product_id: Number(row.product_id),
    code: String(row.code),
    status: row.status as VoucherStatus,
    order_id: row.order_id == null ? null : String(row.order_id),
    sold_at: row.sold_at == null ? null : toIso(row.sold_at),
    used_at: row.used_at == null ? null : toIso(row.used_at),
    created_at: toIso(row.created_at),
  };
}

function asVoucherRow(row: Record<string, unknown>): VoucherRow {
  return {
    ...asVoucher(row),
    product_name: String(row.product_name ?? ""),
    brand: String(row.brand ?? ""),
    usd_value: Number(row.usd_value ?? 0),
    tx_hash: row.tx_hash == null ? null : String(row.tx_hash),
    order_status: row.order_status == null ? null : String(row.order_status),
  };
}

const DDL = [
  `CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    brand TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT NOT NULL,
    usd_value DOUBLE PRECISION NOT NULL,
    price_micro BIGINT NOT NULL,
    theme TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS orders (
    id TEXT PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(id),
    quantity INTEGER NOT NULL,
    buyer_address TEXT,
    amount_micro BIGINT NOT NULL,
    derivation_index INTEGER NOT NULL,
    tx_hash TEXT UNIQUE,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    paid_at TIMESTAMPTZ
  )`,
  `CREATE TABLE IF NOT EXISTS vouchers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL REFERENCES products(id),
    code TEXT UNIQUE NOT NULL,
    status TEXT NOT NULL,
    order_id TEXT REFERENCES orders(id),
    sold_at TIMESTAMPTZ,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS vouchers_product_status_idx ON vouchers (product_id, status)`,
  `CREATE INDEX IF NOT EXISTS orders_status_idx ON orders (status)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS orders_live_hd_idx
     ON orders (derivation_index)
     WHERE status IN ('pending', 'paid')`,
  `CREATE OR REPLACE FUNCTION reserve_shop_order(
     p_id TEXT,
     p_product_id INTEGER,
     p_quantity INTEGER,
     p_buyer TEXT,
     p_amount BIGINT,
     p_created TIMESTAMPTZ,
     p_index INTEGER
   ) RETURNS SETOF orders
   LANGUAGE plpgsql AS $$
   DECLARE
     v_reserved INTEGER;
   BEGIN
     INSERT INTO orders (
       id, product_id, quantity, buyer_address, amount_micro,
       derivation_index, tx_hash, status, created_at, paid_at
     ) VALUES (
       p_id, p_product_id, p_quantity, p_buyer, p_amount,
       p_index, NULL, 'pending', p_created, NULL
     );

     UPDATE vouchers
        SET status = 'reserved', order_id = p_id
      WHERE id IN (
        SELECT id
          FROM vouchers
         WHERE product_id = p_product_id
           AND status = 'available'
         ORDER BY id
         FOR UPDATE SKIP LOCKED
         LIMIT p_quantity
      );
     GET DIAGNOSTICS v_reserved = ROW_COUNT;
     IF v_reserved < p_quantity THEN
       RAISE EXCEPTION 'Not enough vouchers in stock';
     END IF;

     RETURN QUERY SELECT * FROM orders WHERE id = p_id;
   END;
   $$`,
];

async function applySchema() {
  const sql = getSql();
  for (const statement of DDL) {
    await sql.query(statement);
  }
}

async function seedIfEmpty() {
  const sql = getSql();
  const now = new Date().toISOString();
  for (const [index, item] of CATALOG.entries()) {
    const id = index + 1;
    const usd_value = fromMicroUsdc(toMicroUsdc(item.usdValue));
    const price_micro = Number(toMicroUsdc(item.usdValue));
    await sql`
      INSERT INTO products (
        id, slug, brand, name, description, category,
        usd_value, price_micro, theme, active, created_at
      ) VALUES (
        ${id}, ${item.slug}, ${item.brand}, ${item.name}, ${item.description},
        ${item.category}, ${usd_value}, ${price_micro}, ${item.theme}, 1, ${now}
      )
      ON CONFLICT (slug) DO UPDATE SET
        brand = EXCLUDED.brand,
        name = EXCLUDED.name,
        description = EXCLUDED.description,
        category = EXCLUDED.category,
        usd_value = EXCLUDED.usd_value,
        price_micro = EXCLUDED.price_micro,
        theme = EXCLUDED.theme
    `;
  }

  const [{ count }] = (await sql`SELECT COUNT(*)::int AS count FROM vouchers`) as {
    count: number;
  }[];
  if (count > 0) return;

  const products = (await sql`SELECT id, slug FROM products ORDER BY id`) as {
    id: number;
    slug: string;
  }[];
  let nextId = 1;
  for (const product of products) {
    for (let i = 0; i < 12; i += 1) {
      await sql`
        INSERT INTO vouchers (id, product_id, code, status, created_at)
        VALUES (
          ${nextId}, ${product.id}, ${voucherCode(`${product.slug}:${i}`)},
          'available', ${now}
        )
      `;
      nextId += 1;
    }
  }
  const amazon = products.find((product) => product.slug === "amazon");
  const netflix = products.find((product) => product.slug === "netflix");
  if (amazon) {
    await sql`
      INSERT INTO vouchers (
        id, product_id, code, status, sold_at, used_at, created_at
      ) VALUES (
        ${nextId}, ${amazon.id}, ${voucherCode("amazon:used")},
        'used', ${now}, ${now}, ${now}
      )
    `;
    nextId += 1;
  }
  if (netflix) {
    await sql`
      INSERT INTO vouchers (id, product_id, code, status, created_at)
      VALUES (
        ${nextId}, ${netflix.id}, ${voucherCode("netflix:expired")},
        'expired', ${now}
      )
    `;
  }
  await sql.query(
    `SELECT setval(pg_get_serial_sequence('vouchers', 'id'), (SELECT COALESCE(MAX(id), 1) FROM vouchers))`
  );
}

export async function ensureNeonShop() {
  if (!globalForNeonShop.__voucherShopNeonReady) {
    globalForNeonShop.__voucherShopNeonReady = (async () => {
      await applySchema();
      await seedIfEmpty();
    })().catch((error) => {
      globalForNeonShop.__voucherShopNeonReady = undefined;
      throw error;
    });
  }
  await globalForNeonShop.__voucherShopNeonReady;
}

export async function neonListProducts(): Promise<Product[]> {
  await ensureNeonShop();
  const rows = await getSql()`
    SELECT * FROM products WHERE active = 1 ORDER BY id
  `;
  return rows.map((row) => asProduct(row as Record<string, unknown>));
}

export async function neonListAllProducts(): Promise<Product[]> {
  await ensureNeonShop();
  const rows = await getSql()`SELECT * FROM products ORDER BY id`;
  return rows.map((row) => asProduct(row as Record<string, unknown>));
}

export async function neonGetProduct(id: number): Promise<Product | undefined> {
  await ensureNeonShop();
  const rows = await getSql()`SELECT * FROM products WHERE id = ${id} LIMIT 1`;
  const row = rows[0] as Record<string, unknown> | undefined;
  return row ? asProduct(row) : undefined;
}

export async function neonGetProductBySlug(
  slug: string
): Promise<Product | undefined> {
  await ensureNeonShop();
  const rows = await getSql()`SELECT * FROM products WHERE slug = ${slug} LIMIT 1`;
  const row = rows[0] as Record<string, unknown> | undefined;
  return row ? asProduct(row) : undefined;
}

export async function neonCountAvailable(productId: number): Promise<number> {
  await ensureNeonShop();
  const rows = await getSql()`
    SELECT COUNT(*)::int AS count
      FROM vouchers
     WHERE product_id = ${productId} AND status = 'available'
  `;
  return Number((rows[0] as { count: number }).count);
}

export async function neonHeldIndexes(): Promise<number[]> {
  await ensureNeonShop();
  const rows = await getSql()`
    SELECT derivation_index
      FROM orders
     WHERE status IN ('pending', 'paid')
  `;
  return rows.map((row) => Number((row as { derivation_index: number }).derivation_index));
}

export async function neonCreateOrder(input: {
  id: string;
  productId: number;
  quantity: number;
  buyerAddress?: string;
  amountMicro: number;
  createdAt: string;
  derivationIndex: number;
}): Promise<Order> {
  await ensureNeonShop();
  try {
    const rows = await getSql()`
      SELECT * FROM reserve_shop_order(
        ${input.id},
        ${input.productId},
        ${input.quantity},
        ${input.buyerAddress ?? null},
        ${input.amountMicro},
        ${input.createdAt}::timestamptz,
        ${input.derivationIndex}
      )
    `;
    const row = rows[0] as Record<string, unknown> | undefined;
    if (!row) throw new Error("Could not create order");
    return asOrder(row);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (message.includes("Not enough vouchers in stock")) {
      throw new Error("Not enough vouchers in stock");
    }
    throw error;
  }
}

export async function neonListPendingOrders(): Promise<Order[]> {
  await ensureNeonShop();
  const rows = await getSql()`
    SELECT * FROM orders WHERE status = 'pending' ORDER BY created_at
  `;
  return rows.map((row) => asOrder(row as Record<string, unknown>));
}

export async function neonExpireOrder(orderId: string): Promise<boolean> {
  await ensureNeonShop();
  const sql = getSql();
  const [orders] = await sql.transaction((txn) => [
    txn`
      UPDATE orders
         SET status = 'expired'
       WHERE id = ${orderId} AND status = 'pending'
       RETURNING id
    `,
    txn`
      UPDATE vouchers
         SET status = 'available', order_id = NULL
       WHERE order_id = ${orderId} AND status = 'reserved'
    `,
  ]);
  return orders.length > 0;
}

export async function neonApplyVerifiedPayment(
  orderId: string,
  txHash: string
): Promise<boolean> {
  await ensureNeonShop();
  const sql = getSql();
  const taken = await sql`
    SELECT id FROM orders WHERE tx_hash = ${txHash} AND id <> ${orderId} LIMIT 1
  `;
  if (taken.length) return false;
  const existing = await sql`SELECT * FROM orders WHERE id = ${orderId} LIMIT 1`;
  const row = existing[0] as Record<string, unknown> | undefined;
  if (!row) return false;
  const order = asOrder(row);
  if (order.status === "paid") {
    return (order.tx_hash ?? "").toLowerCase() === txHash.toLowerCase();
  }
  const now = new Date().toISOString();
  const updated = await sql`
    UPDATE orders
       SET status = 'paid',
           tx_hash = ${txHash},
           paid_at = ${now}::timestamptz
     WHERE id = ${orderId}
       AND status IN ('pending', 'expired')
     RETURNING id
  `;
  if (!updated.length) return false;
  await sql`
    UPDATE vouchers
       SET status = 'sold',
           sold_at = ${now}::timestamptz
     WHERE order_id = ${orderId} AND status = 'reserved'
  `;
  const attached = await sql`
    SELECT COUNT(*)::int AS count
      FROM vouchers
     WHERE order_id = ${orderId} AND status = 'sold'
  `;
  const need = order.quantity - Number((attached[0] as { count: number }).count);
  if (need > 0) {
    await sql`
      UPDATE vouchers
         SET status = 'sold',
             order_id = ${orderId},
             sold_at = ${now}::timestamptz
       WHERE id IN (
         SELECT id
           FROM vouchers
          WHERE product_id = ${order.product_id}
            AND status = 'available'
            AND order_id IS NULL
          ORDER BY id
          LIMIT ${need}
       )
    `;
  }
  const paid = await neonGetOrder(orderId);
  return paid?.status === "paid";
}

export async function neonGetOrder(id: string): Promise<Order | undefined> {
  await ensureNeonShop();
  const rows = await getSql()`SELECT * FROM orders WHERE id = ${id} LIMIT 1`;
  const row = rows[0] as Record<string, unknown> | undefined;
  return row ? asOrder(row) : undefined;
}

export async function neonSetOrderTxHash(
  id: string,
  txHash: string
): Promise<boolean> {
  await ensureNeonShop();
  const sql = getSql();
  const existing = await sql`
    SELECT id FROM orders WHERE tx_hash = ${txHash} LIMIT 1
  `;
  if (existing.length) return false;
  const rows = await sql`
    UPDATE orders
       SET tx_hash = ${txHash}
     WHERE id = ${id}
       AND status <> 'expired'
       AND tx_hash IS NULL
     RETURNING id
  `;
  return rows.length > 0;
}

export async function neonFulfillOrder(orderId: string): Promise<void> {
  await ensureNeonShop();
  const sql = getSql();
  const now = new Date().toISOString();
  await sql.transaction((txn) => [
    txn`
      UPDATE orders
         SET status = 'paid', paid_at = ${now}::timestamptz
       WHERE id = ${orderId} AND status <> 'expired'
    `,
    txn`
      UPDATE vouchers
         SET status = 'sold', sold_at = ${now}::timestamptz
       WHERE order_id = ${orderId} AND status = 'reserved'
    `,
  ]);
}

export async function neonGetVouchersByOrder(orderId: string): Promise<Voucher[]> {
  await ensureNeonShop();
  const rows = await getSql()`
    SELECT * FROM vouchers WHERE order_id = ${orderId} ORDER BY id
  `;
  return rows.map((row) => asVoucher(row as Record<string, unknown>));
}

export async function neonGetVoucherById(
  id: number
): Promise<VoucherRow | undefined> {
  await ensureNeonShop();
  const rows = await getSql()`
    SELECT
      v.*,
      p.name AS product_name,
      p.brand,
      p.usd_value,
      o.tx_hash,
      o.status AS order_status
    FROM vouchers v
    JOIN products p ON p.id = v.product_id
    LEFT JOIN orders o ON o.id = v.order_id
    WHERE v.id = ${id}
    LIMIT 1
  `;
  const row = rows[0] as Record<string, unknown> | undefined;
  return row ? asVoucherRow(row) : undefined;
}

export async function neonGetVoucherByCode(
  code: string
): Promise<Voucher | undefined> {
  await ensureNeonShop();
  const rows = await getSql()`SELECT * FROM vouchers WHERE code = ${code} LIMIT 1`;
  const row = rows[0] as Record<string, unknown> | undefined;
  return row ? asVoucher(row) : undefined;
}

export async function neonAddVouchers(
  productId: number,
  codes: string[]
): Promise<void> {
  await ensureNeonShop();
  const sql = getSql();
  const product = await neonGetProduct(productId);
  if (!product) throw new Error("Product not found");
  const now = new Date().toISOString();
  for (const raw of codes) {
    const code = raw.trim();
    if (!code) continue;
    try {
      await sql`
        INSERT INTO vouchers (product_id, code, status, created_at)
        VALUES (${productId}, ${code}, 'available', ${now})
      `;
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      if (message.includes("vouchers_code") || message.includes("duplicate")) {
        throw new Error(`Code already exists: ${code}`);
      }
      throw error;
    }
  }
}

export async function neonListVouchers(filter?: {
  status?: string;
  query?: string;
}): Promise<VoucherRow[]> {
  await ensureNeonShop();
  const rows = await getSql()`
    SELECT
      v.*,
      p.name AS product_name,
      p.brand,
      p.usd_value,
      o.tx_hash,
      o.status AS order_status
    FROM vouchers v
    JOIN products p ON p.id = v.product_id
    LEFT JOIN orders o ON o.id = v.order_id
    ORDER BY v.id DESC
  `;
  return rows
    .map((row) => asVoucherRow(row as Record<string, unknown>))
    .filter((voucher) => {
      if (
        filter?.status &&
        filter.status !== "all" &&
        voucher.status !== filter.status
      ) {
        return false;
      }
      if (filter?.query) {
        const hay =
          `${voucher.code} ${voucher.product_name} ${voucher.brand} ${voucher.order_id ?? ""}`.toLowerCase();
        if (!hay.includes(filter.query.toLowerCase())) return false;
      }
      return true;
    });
}

export async function neonVoucherStats() {
  await ensureNeonShop();
  const rows = await getSql()`
    SELECT
      COUNT(*)::int AS total,
      COUNT(*) FILTER (WHERE status = 'available')::int AS available,
      COUNT(*) FILTER (WHERE status = 'used')::int AS used,
      COUNT(*) FILTER (WHERE status = 'expired')::int AS expired
    FROM vouchers
  `;
  const row = rows[0] as {
    total: number;
    available: number;
    used: number;
    expired: number;
  };
  return {
    total: Number(row.total),
    available: Number(row.available),
    used: Number(row.used),
    expired: Number(row.expired),
  };
}

export async function neonListRecentActivity(limit = 8): Promise<VoucherRow[]> {
  const rows = await neonListVouchers();
  return rows
    .filter((voucher) => ["sold", "used", "reserved"].includes(voucher.status))
    .sort((left, right) => {
      const leftAt = left.used_at ?? left.sold_at ?? left.created_at;
      const rightAt = right.used_at ?? right.sold_at ?? right.created_at;
      return rightAt.localeCompare(leftAt);
    })
    .slice(0, limit);
}

export async function neonIsTxHashUsed(txHash: string): Promise<boolean> {
  await ensureNeonShop();
  const rows = await getSql()`
    SELECT 1 FROM orders WHERE tx_hash = ${txHash} LIMIT 1
  `;
  return rows.length > 0;
}

export async function neonRedeemVoucher(
  code: string
): Promise<{ ok: true } | { ok: false; error: string }> {
  const voucher = await neonGetVoucherByCode(code);
  if (!voucher) return { ok: false, error: "Voucher not found" };
  if (voucher.status === "available" || voucher.status === "reserved") {
    return { ok: false, error: "Voucher has not been purchased yet" };
  }
  if (voucher.status === "used") {
    return { ok: false, error: "Voucher already redeemed" };
  }
  if (voucher.status === "expired") {
    return { ok: false, error: "Voucher has expired" };
  }
  const now = new Date().toISOString();
  await getSql()`
    UPDATE vouchers
       SET status = 'used', used_at = ${now}::timestamptz
     WHERE id = ${voucher.id} AND status = 'sold'
  `;
  return { ok: true };
}
